name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npmjs:
    runs-on: ubuntu-latest
    # Dummy env for tests
    env:
      LOCAL_RPC: ws://localhost:8545
      MAINNET_RPC: wss://mainnet.infura.io/ws/v3/${{secrets.INFURA_API_KEY}}
      ROPSTEN_RPC: wss://ropsten.infura.io/ws/v3/${{secrets.INFURA_API_KEY}}
      KOVAN_RPC: wss://kovan.infura.io/ws/v3/${{secrets.INFURA_API_KEY}}
      RINKEBY_RPC: wss://rinkeby.infura.io/ws/v3/${{secrets.INFURA_API_KEY}}
      GOERLI_RPC: wss://goerli.infura.io/ws/v3/${{secrets.INFURA_API_KEY}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16"
          registry-url: https://registry.npmjs.org/
      # Set login for package registries
      - run: npm set //registry.npmjs.org/:_authToken=${{secrets.NPMJS_TOKEN}}
      - run: npm set //npm.pkg.github.com/:_authToken=${{secrets.GPR_TOKEN}}
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}

  publish-gpr:
    runs-on: ubuntu-latest
    # Dummy env for tests
    env:
      LOCAL_RPC: ws://localhost:8545
      MAINNET_RPC: wss://mainnet.infura.io/ws/v3/${{secrets.INFURA_API_KEY}}
      ROPSTEN_RPC: wss://ropsten.infura.io/ws/v3/${{secrets.INFURA_API_KEY}}
      KOVAN_RPC: wss://kovan.infura.io/ws/v3/${{secrets.INFURA_API_KEY}}
      RINKEBY_RPC: wss://rinkeby.infura.io/ws/v3/${{secrets.INFURA_API_KEY}}
      GOERLI_RPC: wss://goerli.infura.io/ws/v3/${{secrets.INFURA_API_KEY}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16"
          registry-url: https://npm.pkg.github.com/
      # Set login for package registries (only required for private dependencies)
      - run: npm set //registry.npmjs.org/:_authToken=${{secrets.NPMJS_TOKEN}}
      - run: npm set //npm.pkg.github.com/:_authToken=${{secrets.GPR_TOKEN}}
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
